default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: idempotency_keys_demo
  password: password
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: idempotency_keys_demo_development

test:
  <<: *default
  database: idempotency_keys_demo_test

production:
  <<: *default
  database: idempotency_keys_demo_production
  username: idempotency_keys_demo
  password: <%= ENV["IDEMPOTENCY_KEYS_DEMO_DATABASE_PASSWORD"] %>
